### PR TITLE
[SPRNEW-1043] Bump rails to 6.1.4

### PR DESCRIPTION
**Pull request by maxicecilia**
Bump rails to 6.1.4

### CODE REVIEW

**Review by vbrodsky — COMMENTED** [review]
2 questions:
is this the latest 6.1.x release?
did you not need to update `Rails.application.config.load_defaults 6.0` in config/application.rb?

**Comment by maxicecilia** [comment]
> 2 questions:
> is this the latest 6.1.x release?
> did you not need to update `Rails.application.config.load_defaults 6.0` in config/application.rb?

1. yes, 6.1.4 is the last version, released in June
2. looks like it's not required, since it will use `:zeitwerk` for any number bigger than 6.0, do you think it's still better to do it?

**Comment by vbrodsky** [comment]
If you say it's not required I trust you :)

**Review by vbrodsky — APPROVED** [review]
why was bootstrap updated?

**Comment by vbrodsky** [comment]
I think you meant your comments for the rails pr, not ruby
I will approve that one too

**Comment by maxicecilia** [comment]
> why was bootstrap updated?

I had to update the major accepted version, otherwise it fails in the main app.

**Pull request merged**
